# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 796)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 796))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 796))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 381))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(399, 0, 880, 777))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 878, 775))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 881, 771))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 382, 400, 395))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(self.frame)
        self.listView.setGeometry(QtCore.QRect(0, 60, 400, 330))
        self.listView.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_sys = QtWidgets.QMenu(self.menubar)
        self.menu_sys.setObjectName("menu_sys")
        MainWindow.setMenuBar(self.menubar)
        self.action_heat = QtWidgets.QAction(MainWindow)
        self.action_heat.setObjectName("action_heat")
        self.action_evaluate = QtWidgets.QAction(MainWindow)
        self.action_evaluate.setObjectName("action_evaluate")
        self.action_price = QtWidgets.QAction(MainWindow)
        self.action_price.setObjectName("action_price")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_out = QtWidgets.QAction(MainWindow)
        self.action_out.setObjectName("action_out")
        self.action_up = QtWidgets.QAction(MainWindow)
        self.action_up.setObjectName("action_up")
        self.menu.addAction(self.action_heat)
        self.menu.addAction(self.action_evaluate)
        self.menu.addAction(self.action_price)
        self.menu.addAction(self.action_up)
        self.menu_sys.addAction(self.action_about)
        self.menu_sys.addAction(self.action_out)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_sys.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "电商管家"))
        self.label.setText(_translate("MainWindow", "关注商品列表"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_sys.setTitle(_translate("MainWindow", "系统"))
        self.action_heat.setText(_translate("MainWindow", "外设产品热卖榜"))
        self.action_heat.setIconText(_translate("MainWindow", "外设产品热卖榜"))
        self.action_heat.setToolTip(_translate("MainWindow", "外设产品热卖榜"))
        self.action_evaluate.setText(_translate("MainWindow", "关注商品--中差评预警"))
        self.action_price.setText(_translate("MainWindow", "关注商品--价格变化预警"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action_out.setText(_translate("MainWindow", "退出"))
        self.action_up.setText(_translate("MainWindow", "更新关注商品信息"))

